# Generated by Django 5.1.7 on 2025-04-07 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clanmember',
            name='current_points',
        ),
    ]
