# Generated by Django 5.1.7 on 2025-04-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_clanmember_current_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clanmember',
            old_name='display_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_points',
            new_name='points',
        ),
        migrations.AddField(
            model_name='event',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
