# Generated by Django 5.1.7 on 2025-04-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_display_name_clanmember_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanmember',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
