# Generated by Django 5.1.7 on 2025-04-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_clanmember_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clanmember',
            options={'ordering': ['name']},
        ),
    ]
